### ISSUE TITLE
Data do meetup de junho de 2019

### ISSUE THREAD

**Issue by caioflores** [react-sanca/meetups#4]
Qual seria o melhor dia para o meetup de Junho?
Votem com 👍 nas datas que vocês estão disponíveis!

Nós vamos usar essa pesquisa para fechar a data do meetup.

Participem do canal react-sanca no slack do react brasil: [react-sanca](https://react-brasil-slack.herokuapp.com/)

**Comment by caioflores** [comment]
17/06/2019 - segunda

**Comment by caioflores** [comment]
18/06/2019 - terça

**Comment by caioflores** [comment]
19/06/2019 - quarta (pré-feriado)

**Comment by caioflores** [comment]
24/06/2019 - segunda

**Comment by caioflores** [comment]
25/06/2019 - terça

**Comment by caioflores** [comment]
26/06/2019 - quarta

**Comment by caioflores** [comment]
27/06/2019 - quinta

**Comment by marcel0ll** [comment]
Dia 26 fecharam o OpenTalks la na arquivei, acho que seria melhor não marcar nesse dia

**Comment by caioflores** [comment]
Fala galera! Fechamos de juntar o meetup de React com o Open Talks esse mês pra integrar as comunidades!! Então vai ser no dia 26
